import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  Folders,
  type Icon as LucideIcon,
  DatabaseBackup,
  CandlestickChart,
  ArrowRightToLine,
  ArrowLeftToLine,
  Maximize,
  Home, Search, ListFilter,
} from 'lucide-react';

export type Icon = typeof LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  folders: Folders,
  databaseBackup: DatabaseBackup,
  statistics: CandlestickChart,
  rightIcon: ArrowRightToLine,
  leftIcon: ArrowLeftToLine,
  maximize: Maximize,
  home: Home,
  search:Search,
  listFilter:ListFilter
};
